// examples/vue/src/App.vue
<script setup lang="ts">

import { defineSolvimonAddPaymentMethodForm } from '@solvimon/sdk/solvimon-add-payment-method-form';

defineSolvimonAddPaymentMethodForm();
</script>

<template>
  <main>
    <solvimon-add-payment-method-form token="S3JZMVgyZEVhZkduaFZkcWhLMncxRTZLa2NTQ0x3cDkucHVybF9td0RlZUEwdUhvc3ZWT0FSZTQxcg==" environment="DEV" />
  </main>
</template>

// examples/next/app/page.tsx
'use client'; // Ensure this file is treated as a client component

import { useEffect } from 'react';
import styles from './page.module.css';

export default function Home() {
  useEffect(() => {
    async function loadSolvimonSdk() {
      const { defineSolvimonAddPaymentMethodForm } = await import('@solvimon/sdk/solvimon-add-payment-method-form');
      defineSolvimonAddPaymentMethodForm();
    }
    
    loadSolvimonSdk();
  }, []);

  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <solvimon-add-payment-method-form token="S3JZMVgyZEVhZkduaFZkcWhLMncxRTZLa2NTQ0x3cDkucHVybF9td0RlZUEwdUhvc3ZWT0FSZTQxcg==" environment="DEV" />
      </main>
    </div>
  );
}
